services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - prometheus
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./best_model.pth:/app/best_model.pth


  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.14.0
    ports:
      - '5000:5000'
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --serve-artifacts
      --allowed-hosts "mlflow,mlflow:5000,localhost,localhost:5000"
    volumes:
      - ./mlflow-data:/mlflow

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: